"""add job table

Revision ID: 48850cba590f
Revises: 
Create Date: 2026-08-31 23:00:18.752340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48850cba590f'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('quoted', 'measured', 'cancelled') OR scheduled_date IS NOT NULL", name=op.f('ck_job_scheduled_date_required')),
    sa.CheckConstraint("status IN ('quoted', 'measured', 'scheduled', 'ordered', 'arrived', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_job_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_scheduled_date'), 'job', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_scheduled_date'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
